FROM node:22-alpine

WORKDIR /app

COPY tsconfig.json package.json package-lock.json ./
COPY src ./src

RUN npm install

RUN npm run build

ENV PORT=3002
ENV VERSION=1.2.3.4.5.6

CMD ["npm", "run", "start"]

# docker build -t onestage -f Dockerfile.one .
# docker run -p 3002:3002 onestage