name: key-value-app

services:
  db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - "27017:27017"
    environment:
      - name=value
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - mongodb-network

volumes:
  mongodb-data:

networks:
  mongodb-network:










# docker run --rm --name debugsb -it --network 8docker_compose_default mongodb/mongodb-community-server:7.0-ubuntu2204 mongosh mongodb://8docker_compose-db-1