FROM node:22.12.0-alpine AS build

ENV host=0.0.0.0

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]



# docker build -t vite:dev -f Dockerfile.dev .
# docker run -p 5173:5173 -v ${pwd}/public:/app/public -v ${pwd}/src:/app/src vite:dev