name: notes-app

services:

  notes-backend:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PORT=80
      - MONGODB_HOST=notes-db
    
    env_file:
      - .env

    ports:
      - 3000:80
    
    networks:
      - notes-network
    
    depends_on:
      - notes-db
    
    volumes:
      - type: bind
        source: ./src
        target: /app/src

  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204

    env_file:
      - .env
    
    # ports:
    #   - 27017:27017
    
    networks:
      - notes-network
    
    volumes:
      - type: volume
        source: notes-volume
        target: /data/db
      
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true



networks:
  notes-network:

volumes:
  notes-volume:
