FROM node:22.12.0-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .

RUN npm i

ENV PORT=4000

CMD ["npm", "run", "dev"]

# docker build -f Dockerfile.express.dev -t express:dev .
# docker run -p 3000:4000 -v ${pwd}/src:/app/src --network key-value-network express:dev