FROM node:22.12.0-alpine AS build

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .

RUN npm run build

FROM node:22.12.0-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY package.json .
COPY package-lock.json .

RUN npm i --omit=dev

ENV PORT=4000

CMD ["npm", "start"]

# docker build -f Dockerfile.express -t express:build .
# docker run -p 3000:4000 express:build